### ISSUE TITLE
WATC FDSN ip address

### ISSUE THREAD

**Issue by davidfee5** [uafgeotools/waveform_collection#5]
From my office I typically point to http://10.30.6.3:8080 for the WATC FDSN server, while 10.30.5.10:8080 is for when I'm out of the office and connected via vpn. Should we allow for both ips or maybe make the user connect through a vpn? Or maybe mess with my routing tables?

**Comment by liamtoney** [comment]
Just a note that I tried this recently and `supersonic-nagnet` didn't work for me — I got this error:
```
ValueError: The FDSN service base URL `http://supersonic-nagnet:8080` is not a valid URL.
```
Looks like their URL validator doesn't like hyphens. Changing to `supersonic_nagnet` worked for me.
